[package]
name = "internet-use"
version = "0.1.0"
edition = "2024"

[dependencies]
fantoccini = "0.21.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
